# Generated by Django 4.0.5 on 2022-06-24 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InnotterPage', '0002_alter_page_owner_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='pages', to='InnotterPage.tag'),
        ),
    ]
