# Generated by Django 4.0.5 on 2022-07-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InnotterPage', '0006_remove_page_follow_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
