version: '3.10'
services:
  web:
    restart: on-failure
    volumes:
      - ./core_app:/app
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    entrypoint:
      - ./django-entrypoint.sh
    depends_on:
      - rabbit
      - db
      - celery
      - fastapi
    links:
      - rabbit
      - fastapi
      - celery

  rabbit:
    image: rabbitmq:3.10.5-management
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  celery:
    restart: always
    volumes:
      - ./core_app:/app
    build:
      context: .
    env_file:
      - ./.env
    entrypoint:
      - ./celery-entrypoint.sh
    depends_on:
      - rabbit
      - db
    links:
      - rabbit

  fastapi:
    restart: always
    volumes:
      - ./microservice:/app
    build:
      context: .
    env_file:
      - ./.env
    entrypoint:
      ./fast-api-entrypoint.sh
    depends_on:
      - rabbit
      - mongo
    ports:
      - "80:80"
    links:
      - rabbit

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"

volumes:
  postgres_data:
