# Generated by Django 4.0.5 on 2022-06-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("innotter_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
