# Generated by Django 4.0.6 on 2022-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innotter_user", "0004_user_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
