# Generated by Django 4.0.6 on 2022-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innotter_user", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
