# Generated by Django 4.0.5 on 2022-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innotter_user", "0006_alter_user_title_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(default="Untitled", max_length=80),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, default="User", max_length=255, unique=True
            ),
        ),
    ]
