# Generated by Django 4.0.5 on 2022-07-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberequest',
            old_name='is_accept',
            new_name='is_accepted',
        ),
    ]
