# Generated by Django 4.0.5 on 2022-06-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innotter_tag", "0001_initial"),
        ("innotter_page", "0004_alter_page_followers_alter_page_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AlterField(
            model_name="page",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="pages", to="innotter_tag.tag"
            ),
        ),
    ]
