# Generated by Django 4.0.5 on 2022-07-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("innotter_page", "0005_delete_tag_alter_page_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="follow_requests",
        ),
    ]
